### PR TITLE
Braking changes! (reexport and examples.rs)

### PR DESCRIPTION
**Pull request by paulosuzart**
- reexport only required types inside lib: NodeInfo and HashRing
- removed example.rs. Now tests are inside hash_ring

It is more practical if lib users just do `use hash_ring::HashRing` instead of `hash_ring::hash_ring::HashRing`.

Also made NodeInfo the default information holder that can be used by users so they optionally create theirs.

As a last change, example.rs was removed and replaced by tests with assertions.

### CODE REVIEW

**Comment by mattnenterprise** [comment]
Could you also update the README? it contains the example.rs code inside of it.

**Comment by paulosuzart** [comment]
Just did. But I think I can remove the NodeInfo and also use the provide one. Let me do that.

**Comment by mattnenterprise** [comment]
It has been push to crates.io!

**Comment by paulosuzart** [comment]
This is awesome. Hope it can be the perfect fit to the other project. Thanks a lot.

**Pull request merged**
